# Generated by Django 4.0.2 on 2022-03-06 21:38

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coursesubmission',
            constraint=models.CheckConstraint(check=models.Q(('id', django.db.models.expressions.F('parent_submission_id')), _negated=True), name='course_submission_parent_not_self_referencing'),
        ),
    ]
