# Generated by Django 4.0.5 on 2022-08-09 18:30

from django.db import migrations, models
import django.db.models.deletion
import django_update_from_dict


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_comment_coursesubmissionfieldcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSubmissionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_index', models.PositiveIntegerField()),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.comment')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursemembership')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursesubmission')),
            ],
            bases=(django_update_from_dict.UpdateFromDictMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='CourseSubmissionFieldComment',
        ),
        migrations.AddConstraint(
            model_name='coursesubmissioncomment',
            constraint=models.UniqueConstraint(fields=('submission_id', 'comment_id'), name='unique_submission_comment'),
        ),
    ]
