# Generated by Django 4.0.2 on 2022-03-07 17:12

from django.db import migrations, models
import django.db.models.deletion
import django_update_from_dict


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursesubmission_course_submission_parent_not_self_referencing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show_group_members_names', models.BooleanField()),
                ('allow_member_group_creation', models.BooleanField()),
                ('milestone_alias', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'course settings',
            },
            bases=(django_update_from_dict.UpdateFromDictMixin, models.Model),
        ),
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursemember',
            name='role',
            field=models.CharField(choices=[('CO-OWNER', 'Co Owner'), ('INSTRUCTOR', 'Instructor'), ('MEMBER', 'Member')], default='MEMBER', max_length=10),
        ),
        migrations.DeleteModel(
            name='CourseSetting',
        ),
        migrations.AddField(
            model_name='coursesettings',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
