# Generated by Django 4.0.2 on 2022-03-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursesettings_course_is_published_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesettings',
            old_name='allow_member_group_creation',
            new_name='allow_members_to_create_groups',
        ),
    ]
