# Generated by Django 4.0.2 on 2022-03-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_account_type'),
        ('courses', '0004_rename_allow_member_group_creation_coursesettings_allow_members_to_create_groups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseMember',
            new_name='CourseMembership',
        ),
        migrations.RemoveConstraint(
            model_name='coursemembership',
            name='unique_course_member',
        ),
        migrations.AddConstraint(
            model_name='coursemembership',
            constraint=models.UniqueConstraint(fields=('user_id', 'course_id'), name='unique_course_membership'),
        ),
    ]
