# Generated by Django 4.0.2 on 2022-03-08 16:06

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_coursemember_coursemembership_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coursemilestone',
            name='course_milestone_start_date_time_lt_end_date_time',
        ),
        migrations.AlterField(
            model_name='coursemilestone',
            name='end_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddConstraint(
            model_name='coursemilestone',
            constraint=models.CheckConstraint(check=models.Q(('end_date_time__isnull', True), ('start_date_time__lt', django.db.models.expressions.F('end_date_time')), _connector='OR'), name='course_milestone_start_date_time_lt_end_date_time'),
        ),
    ]
