# Generated by Django 4.0.2 on 2022-03-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_coursemilestone_course_milestone_start_date_time_lt_end_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemilestone',
            name='end_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
