# Generated by Django 4.0.2 on 2022-03-08 17:05

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_coursemilestone_end_date_time'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coursemilestone',
            name='course_milestone_start_date_time_lt_end_date_time',
        ),
        migrations.AddConstraint(
            model_name='coursemilestone',
            constraint=models.CheckConstraint(check=models.Q(('start_date_time__lt', django.db.models.expressions.F('end_date_time'))), name='course_milestone_start_date_time_lt_end_date_time'),
        ),
    ]
