# Generated by Django 4.0.2 on 2022-03-18 12:22

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django_update_from_dict
import pigeonhole.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_remove_form_creator'),
        ('courses', '0009_coursesettings_allow_members_to_add_or_remove_group_members_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMilestoneTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=(django_update_from_dict.UpdateFromDictMixin, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name='coursesubmission',
            name='course_submission_parent_not_self_referencing',
        ),
        migrations.RenameField(
            model_name='coursesubmission',
            old_name='associated_group',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='coursesubmission',
            old_name='associated_milestone',
            new_name='milestone',
        ),
        migrations.RenameField(
            model_name='coursesubmission',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='coursesubmission',
            old_name='parent_submission',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='coursesubmission',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursesubmission',
            name='form_response_data',
            field=models.JSONField(blank=True, default=pigeonhole.common.utils.default_list),
        ),
        migrations.AddField(
            model_name='coursesubmission',
            name='is_draft',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursesubmission',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.coursemembership'),
        ),
        migrations.AlterField(
            model_name='coursesubmission',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursemembership'),
        ),
        migrations.AddConstraint(
            model_name='coursesubmission',
            constraint=models.CheckConstraint(check=models.Q(('id', django.db.models.expressions.F('parent_id')), _negated=True), name='course_submission_parent_not_self_referencing'),
        ),
        migrations.AddField(
            model_name='coursemilestonetemplate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursemilestonetemplate',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forms.form'),
        ),
        migrations.AddConstraint(
            model_name='coursemilestonetemplate',
            constraint=models.UniqueConstraint(fields=('course_id', 'form_id'), name='unique_course_form'),
        ),
    ]
