# Generated by Django 4.0.2 on 2022-03-18 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_coursemilestonetemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemilestonetemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursemilestonetemplate',
            name='submission_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Group'), ('INDIVIDUAL/GROUP', 'Individual Group')], default='GROUP', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursesubmission',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coursesubmission',
            name='milestone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursemilestone'),
        ),
    ]
