# Generated by Django 4.0.2 on 2022-03-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_coursemilestonetemplate_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesettings',
            old_name='allow_members_to_add_or_remove_group_members',
            new_name='allow_students_to_add_or_remove_group_members',
        ),
        migrations.RenameField(
            model_name='coursesettings',
            old_name='allow_members_to_create_groups',
            new_name='allow_students_to_create_groups',
        ),
        migrations.RenameField(
            model_name='coursesettings',
            old_name='allow_members_to_delete_groups',
            new_name='allow_students_to_delete_groups',
        ),
        migrations.RenameField(
            model_name='coursesettings',
            old_name='allow_members_to_join_groups',
            new_name='allow_students_to_join_groups',
        ),
        migrations.RenameField(
            model_name='coursesettings',
            old_name='allow_members_to_leave_groups',
            new_name='allow_students_to_leave_groups',
        ),
        migrations.RenameField(
            model_name='coursesettings',
            old_name='allow_members_to_modify_group_name',
            new_name='allow_students_to_modify_group_name',
        ),
        migrations.AlterField(
            model_name='coursemembership',
            name='role',
            field=models.CharField(choices=[('CO-OWNER', 'Co Owner'), ('INSTRUCTOR', 'Instructor'), ('STUDENT', 'Student')], default='STUDENT', max_length=10),
        ),
    ]
