# Generated by Django 4.0.2 on 2022-03-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_rename_allow_members_to_add_or_remove_group_members_coursesettings_allow_students_to_add_or_remove_g'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemilestonetemplate',
            name='is_published',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
