# Generated by Django 4.0.2 on 2022-03-23 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_coursemilestonetemplate_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesubmission',
            old_name='last_updated_by',
            new_name='editor',
        ),
    ]
