# Generated by Django 4.0.5 on 2022-06-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_rename_last_updated_by_coursesubmission_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemilestone',
            name='is_published',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
