# Generated by Django 4.0.5 on 2022-07-23 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_comment_coursesubmissionfieldcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubmissionfieldcomment',
            name='course_membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursemembership'),
        ),
    ]
