# Generated by Django 4.0.2 on 2022-03-23 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_delivery_service', '0001_initial'),
        ('users', '0002_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_delivery_service.image'),
        ),
    ]
